## Installing Dependencies

In [52]:
import pandas as pd
from scipy import stats

In [53]:
data = pd.read_csv('../data/clean_data.csv')
data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,HP,engine_size,n_cylinders
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,Automatic,Black,Black,At least 1 accident or damage reported,Yes,10300.0,300.0,3.7,6.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,NaN,3.8,6.0
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,NaN,NaN,54598.0,NaN,3.5,NaN
3,Infiniti,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,Automatic,Black,Black,NaN,Yes,15500.0,354.0,3.5,6.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,Automatic,Glacier White Metallic,Black,NaN,NaN,34999.0,NaN,2.0,NaN

In [54]:
data.price.isnull().sum()

np.int64(0)

## Does accident history affect car prices?

Null Hypothesis: Cars with accidents have the seame mean price as cars without accidents

Alternate Hypothesis: Cars with accidents have a different mean price

In [55]:
data.accident.unique()

<StringArray>
['At least 1 accident or damage reported', nan]
Length: 2, dtype: str

In [56]:
with_accident = data[data.accident == 'At least 1 accident or damage reported']['price']
without_accident = data[data.accident != 'At least 1 accident or damage reported']['price']

In [57]:
t_stat, p_value = stats.ttest_ind(without_accident, with_accident)
p_value

np.float64(4.3219912229679957e-13)

Since P-Value is less than 0.05. So we will reject the null hypothesis.

So we can say: Accidents history does affect car prices

## Does fuel type affect prices?

Null Hypothesis: The mean prices are equal across all fuel types

Alternate Hypothesis: At least one fuel type has a different mean price

In [58]:
data.fuel_type.value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

In [59]:
gasoline = data[data.fuel_type == 'Gasoline']['price']
hybrid = data[data.fuel_type == 'Hybrid']['price']
e85 = data[data.fuel_type == 'E85 Flex Fuel']['price']
diesel = data[data.fuel_type == 'Diesel']['price']
plug_in = data[data.fuel_type == 'Plug-In Hybrid']['price']

In [60]:
t_stat, p_value = stats.f_oneway(
                    gasoline,
                    hybrid,
                    e85,
                    diesel,
                    plug_in
)

p_value

np.float64(0.017390716945720114)

Since P-Value is less than 0.05. So we will reject the null hypothesis.

So we can say: At least one fuel type has different mean price

## Is mileage correlated with price?

Null Hypothesis: There is no linear correlation

Alternate Hypothesis: There is a significant linear correlation

In [61]:
data[['milage', 'price']].corr()

          milage     price
milage  1.000000 -0.305528
price  -0.305528  1.000000

In [62]:
r_coeff, p_value = stats.pearsonr(data['milage'], data['price'])
r_coeff, p_value

(np.float64(-0.30552806892818085), np.float64(2.224698931004468e-87))

Pearson correlation analysis showed a statistically significant negative correlation between milage and price. This indicates that vehicles with higher mileage tend to have lower prices

## Is horsepower significantly correlated with vehicle price?

Null Hypothesis: There is no linear correlation between horsepower and vehicle price

Alternative Hypothesis: There is a significant linear correlation between horsepower and vehicle price

In [63]:
data.HP.isnull().sum()

np.int64(810)

In [64]:
hp_data = data.dropna(subset=['HP'])

r_coeff, p_value = stats.pearsonr(hp_data['HP'], hp_data['price'])
r_coeff, p_value

(np.float64(0.35403308367680286), np.float64(4.266501995286961e-95))

Since P-Value < 0.05, we will reject null hypothesis.

Pearson correlation analysis relvealed a statistically significant moderate positive correlation between horsepower and vehicle price. This suggests that vehicles with higher horsepower tend to have higher prices